/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.UI;

import deepspace.HangarToUI;
import deepspace.ShieldToUI;
import deepspace.WeaponToUI;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author mario
 */
public class HangarView extends javax.swing.JPanel {
    
    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
		
    }
	
	void setHangar (HangarToUI h){
		if (h != null){
			WeaponView weaponView;

			for (WeaponToUI w : h.getWeapons()) {
					weaponView = new WeaponView();
					weaponView.setWeapon(w);
					jPWeapons.add(weaponView);
			}

			ShieldView shieldView;
			for (ShieldToUI s : h.getShieldBoosters()) {
				shieldView = new ShieldView();
				shieldView.setShield(s);
				jPShields.add(shieldView);
			}
		}
		
	}
	
	ArrayList<Integer> getSelectedWeapons(){
		ArrayList<Integer> selectedWeapons = new ArrayList<>();
        int i = 0;
        for (Component c : jPWeapons.getComponents()) {
            if (((WeaponView) c).isSelected()) {
                selectedWeapons.add(i);
            }
            i++;
        }
        return selectedWeapons;
	}
	
	ArrayList<Integer> getSelectedShields (){
		ArrayList<Integer> selectedHangarShields = new ArrayList<>();
        int i = 0;
        for (Component c : jPShields.getComponents()) {
            if (((ShieldView) c).isSelected()) {
                selectedHangarShields.add(i);
            }
            i++;
        }
        return selectedHangarShields;
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPWeapons = new javax.swing.JPanel();
        jPShields = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(jPWeapons);
        add(jPShields);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPShields;
    private javax.swing.JPanel jPWeapons;
    // End of variables declaration//GEN-END:variables
}
